[package]
name = "mt-discovery"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mt-core = { path = "../mt-core" }
md-5 = "0.10"
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true, features = ["blocking"] }
percent-encoding = "2"

[dev-dependencies]
tempfile = "3"
