//! SRT (SubRip Text) parser and serializer.

use crate::error::ParseError;
use crate::model::{Event, EventKind, Style, Subtitles};

/// Canonical ASS v4+ `[Events]` `Format:` field order (matches pysubs2 output).
pub const DEFAULT_EVENTS_FORMAT: &[&str] = &[
    "Layer", "Start", "End", "Style", "Name", "MarginL", "MarginR", "MarginV", "Effect", "Text",
];

/// Canonical `[V4+ Styles]` `Format:` field order (matches pysubs2 output).
pub const DEFAULT_STYLES_FORMAT: &[&str] = &[
    "Name",
    "Fontname",
    "Fontsize",
    "PrimaryColour",
    "SecondaryColour",
    "OutlineColour",
    "BackColour",
    "Bold",
    "Italic",
    "Underline",
    "StrikeOut",
    "ScaleX",
    "ScaleY",
    "Spacing",
    "Angle",
    "BorderStyle",
    "Outline",
    "Shadow",
    "Alignment",
    "MarginL",
    "MarginR",
    "MarginV",
    "Encoding",
];

/// The raw `Default` style row pysubs2 writes for a format-less document.
pub const DEFAULT_STYLE_RAW: &str = "Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1";

/// `[Script Info]` body lines pysubs2 emits by default.
pub const DEFAULT_SCRIPT_INFO_LINES: &[&str] = &[
    "; Script generated by pysubs2",
    "; https://pypi.python.org/pypi/pysubs2",
    "WrapStyle: 0",
    "ScaledBorderAndShadow: yes",
    "Collisions: Normal",
    "ScriptType: v4.00+",
];

/// Parse an SRT file from a string.
pub fn load_srt(input: &str) -> Result<Subtitles, ParseError> {
    // Strip a leading UTF-8 BOM if present.
    let input = input.strip_prefix('\u{FEFF}').unwrap_or(input);

    let mut events: Vec<Event> = Vec::new();

    // SRT blocks are separated by blank lines.
    // Each block: index line, timing line, text lines.
    let mut block: Vec<&str> = Vec::new();
    // 1-based line number where the current block began.
    let mut block_start_line = 1usize;

    for (idx, line) in input.lines().chain(std::iter::once("")).enumerate() {
        let line_no = idx + 1;
        if line.trim().is_empty() {
            if !block.is_empty() {
                if let Some(event) = parse_srt_block(&block, block_start_line)? {
                    events.push(event);
                }
                block.clear();
            }
        } else {
            if block.is_empty() {
                block_start_line = line_no;
            }
            block.push(line);
        }
    }

    // Mirror pysubs2: an SRT loaded into memory is a fully-styled document with
    // canonical ASS v4+ defaults, so serializing it to ASS yields a valid file.
    Ok(Subtitles {
        bom: false,
        script_info_lines: DEFAULT_SCRIPT_INFO_LINES
            .iter()
            .map(|s| s.to_string())
            .collect(),
        pre_styles_sections: Vec::new(),
        styles_format: DEFAULT_STYLES_FORMAT
            .iter()
            .map(|s| s.to_string())
            .collect(),
        styles: vec![Style {
            name: "Default".to_string(),
            raw: DEFAULT_STYLE_RAW.to_string(),
        }],
        pre_events_sections: Vec::new(),
        events_format: DEFAULT_EVENTS_FORMAT
            .iter()
            .map(|s| s.to_string())
            .collect(),
        events,
        post_events_sections: Vec::new(),
    })
}

fn parse_srt_block(block: &[&str], block_start_line: usize) -> Result<Option<Event>, ParseError> {
    // First line is the sequence number (ignore). Need at least number + timing.
    if block.len() < 2 {
        return Ok(None);
    }

    // Timing is the block's second line.
    let timing_line_no = block_start_line + 1;

    // Second line: "HH:MM:SS,mmm --> HH:MM:SS,mmm"
    let timing_line = block[1].trim();
    let arrow = "-->";
    let pos = timing_line.find(arrow).ok_or_else(|| {
        ParseError::malformed_at(
            format!("no '-->' in timing line: {timing_line}"),
            timing_line_no,
        )
    })?;
    let start_str = timing_line[..pos].trim();
    let end_part = timing_line[pos + arrow.len()..].trim();

    // Handle optional position info after end time
    // (e.g. "00:00:01,000 --> 00:00:02,000  X1:0 X2:0 Y1:0 Y2:0")
    let end_str = end_part.split_whitespace().next().unwrap_or(end_part);

    let start_ms = parse_srt_time(start_str, timing_line_no)?;
    let end_ms = parse_srt_time(end_str, timing_line_no)?;

    // Remaining lines are text
    let text = if block.len() > 2 {
        block[2..].join("\n")
    } else {
        String::new()
    };

    if text.trim().is_empty() {
        return Ok(None);
    }

    Ok(Some(Event {
        kind: EventKind::Dialogue,
        layer: 0,
        start_ms,
        end_ms,
        style: "Default".to_string(),
        name: String::new(),
        margin_l: 0,
        margin_r: 0,
        margin_v: 0,
        effect: String::new(),
        text,
    }))
}

fn parse_srt_time(s: &str, line_no: usize) -> Result<i64, ParseError> {
    // Format: HH:MM:SS,mmm (also accept '.' as the ms separator)
    let s = s.trim();
    let bad = || ParseError::BadTime {
        value: s.to_string(),
        line_no: Some(line_no),
    };

    let sep_pos = s.rfind([',', '.']).ok_or_else(bad)?;
    let hms = &s[..sep_pos];
    let ms_str = &s[sep_pos + 1..];

    let ms: i64 = ms_str.parse().map_err(|_| bad())?;

    let parts = hms.split(':').collect::<Vec<_>>();
    if parts.len() != 3 {
        return Err(bad());
    }
    let h: i64 = parts[0].trim().parse().map_err(|_| bad())?;
    let m: i64 = parts[1].trim().parse().map_err(|_| bad())?;
    let sec: i64 = parts[2].trim().parse().map_err(|_| bad())?;

    Ok(h * 3_600_000 + m * 60_000 + sec * 1_000 + ms)
}

fn format_srt_time(ms: i64) -> String {
    let ms = ms.max(0);
    let h = ms / 3_600_000;
    let m = (ms % 3_600_000) / 60_000;
    let s = (ms % 60_000) / 1_000;
    let millis = ms % 1_000;
    format!("{h:02}:{m:02}:{s:02},{millis:03}")
}

/// Serialize a `Subtitles` to SRT format.
///
/// Only `Dialogue` events are emitted; `Comment` events are skipped.
pub fn to_srt_string(subs: &Subtitles) -> String {
    let mut out = String::new();
    let mut idx = 1usize;

    for event in &subs.events {
        if event.kind != EventKind::Dialogue {
            continue;
        }
        out.push_str(&idx.to_string());
        out.push('\n');
        out.push_str(&format_srt_time(event.start_ms));
        out.push_str(" --> ");
        out.push_str(&format_srt_time(event.end_ms));
        out.push('\n');
        out.push_str(&event.text);
        out.push('\n');
        out.push('\n');
        idx += 1;
    }

    out
}
