DEFAULT_MODEL = "gpt-4o-mini"
DEFAULT_BATCH_SIZE = 50
DEFAULT_SCENE_THRESHOLD = 30.0

PROVIDER_OPENAI = "openai"
PROVIDER_LOCAL = "local"
DEFAULT_PROVIDER = PROVIDER_OPENAI

BIDI_MODEL_NAME = "allegro/BiDi-eng-pol"
DEFAULT_DEVICE = "auto"

LANGUAGE_POLISH = "Polish"
LANGUAGE_ENGLISH = "eng"
LANGUAGE_ENGLISH_SHORT = "en"

EXTENSION_MKV = ".mkv"
EXTENSION_SRT = ".srt"

TRACK_TYPE_SUBTITLE = "subtitles"

POLISH_TRACK_NAME = "Polish (AI)"

ENV_OPENAI_API_KEY = "OPENAI_API_KEY"

LOG_FORMAT = "%(asctime)s - %(levelname)s - %(message)s"
