[package]
name = "mt-subtitles"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
encoding_rs = { workspace = true }
lazy_static = { workspace = true }

mt-core = { workspace = true }
regex = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
encoding_rs = { workspace = true }
serde_json = { workspace = true }
