[package]
name = "mt-media"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dirs = { workspace = true }

mt-core = { workspace = true }
mt-subtitles = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
ttf-parser = { workspace = true }

[dev-dependencies]
