[package]
name = "mt-pipeline"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]

mt-core = { workspace = true }
mt-discovery = { workspace = true }
mt-fetch = { workspace = true }
mt-media = { workspace = true }
mt-ml = { workspace = true }
mt-subtitles = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
