[package]
name = "mt-ml"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]

mt-core = { workspace = true }
mt-media = { workspace = true }
mt-subtitles = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
