[package]
name = "mt-fetch"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
encoding_rs = { workspace = true }
md-5 = { workspace = true }

mt-core = { workspace = true }
mt-discovery = { workspace = true }
mt-subtitles = { workspace = true }
ndarray = { workspace = true }
quick-xml = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true, features = ["blocking", "cookies"] }
scraper = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
urlencoding = { workspace = true }
zip = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
